// <auto-generated />
using System;
using Internship_18_CashRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Internship_18_CashRegister.Data.Migrations
{
    [DbContext(typeof(CashRegisterContext))]
    [Migration("20190627184011_TaxAndEmployeeNameChanged")]
    partial class TaxAndEmployeeNameChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Barcode");

                    b.Property<bool>("IsTaxRateReduced");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("UnitsInStock");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.ArticleReceipt", b =>
                {
                    b.Property<int>("ArticleId");

                    b.Property<int>("ReceiptId");

                    b.Property<int>("Quantity");

                    b.HasKey("ArticleId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ArticleReceipts");
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.CashRegister", b =>
                {
                    b.Property<int>("CashRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CashRegisterId");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId");

                    b.Property<int?>("RegisterCashRegisterId");

                    b.Property<Guid>("SerialNumber");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("ReceiptId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegisterCashRegisterId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.ArticleReceipt", b =>
                {
                    b.HasOne("Internship_18_CashRegister.Data.Entities.Models.Article", "Article")
                        .WithMany("ArticleReceipts")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Internship_18_CashRegister.Data.Entities.Models.Receipt", "Receipt")
                        .WithMany("ArticleReceipts")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Internship_18_CashRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.HasOne("Internship_18_CashRegister.Data.Entities.Models.Employee", "Employee")
                        .WithMany("Receipts")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Internship_18_CashRegister.Data.Entities.Models.CashRegister", "Register")
                        .WithMany("Receipts")
                        .HasForeignKey("RegisterCashRegisterId");
                });
#pragma warning restore 612, 618
        }
    }
}
